### ISSUE TITLE
The seasons don't change

### ISSUE THREAD

**Issue by kubiiikk** [AdvancedPlugins/Seasons#67]
### Describe the bug

If I modify any value in calendar.yml to be higher, like the number of minutes a game day lasts, or how many game days a season should last, the seasons stop changing. In order for the seasons to continue to change, I need to reset all the values ​​to their defaults.

### How to reproduce

Modify any value indicating the time in calendar.yml to a higher one, the seasons will stop.

**Comment by efor89** [comment]
for me the season not change from winter to spring
this makes the season plugin rly bad
pls fix this fast as posibile.

**Comment by kubiiikk** [comment]
> ### Describe the bug
> 
> If I modify any value in calendar.yml to be higher, like the number of minutes a game day lasts, or how many game days a season should last, the seasons stop changing. In order for the seasons to continue to change, I need to reset all the values ​​to their defaults.
> ### How to reproduce
> 
> Modify any value indicating the time in calendar.yml to a higher one, the seasons will stop.
> ### Screenshots / Videos
> 
> _No response_
> ### Server Log
> 
> _No response_



> @efor89 can you share your configuration? It's definitely something with configuration, it's working alright for me with testing.
> 


> @HokoriStan Any worldguard region will be ignored.

Here is my configuration:
[config.txt](https://github.com/AdvancedPlugins/Seasons/files/15214251/config.txt)
[calendar.txt](https://github.com/AdvancedPlugins/Seasons/files/15214252/calendar.txt)

**Comment by efor89** [comment]
i watch now if it is better changing. 
the last winter spring change was working so i w8 for 1 more change.
current its summer, on 26.05 it change from winter to spring again.
i tell you if it works again.

**Comment by Ynverxe** [comment]
@kubiiikk is your problem solved? I noticed that this issue is from Apr 1, since that date five updates were released, maybe your problem was fixed.

If not. I can't reproduce the bug with your configuration. Can you make a video reproducing it?

**Comment by kubiiikk** [comment]
@Ynverxe Unfortunately no, the updates didn't fix the problem. Simply by increasing any value in calendar.yml, the seasons stop at the current one, and I can jump to the next one just by using the command.

The video will be longer, but I will record it in a few hours as soon as I get to the server.

**Comment by kubiiikk** [comment]
Although I don't understand how when it never helped before, after resetting the calendar.yml I'd say it works. I'll let it run and let you know tomorrow morning if it works without any issues.

**Comment by kubiiikk** [comment]
After restarting the server in the morning (3:00) the seasons do not change again, there is not a single mention in the log (I have events set for every month). During the day, I tried to change the settings and length of days, only the default setting works.

**Comment by efor89** [comment]
this time summer to fall was not working.
but i change the default temperatur 2 days ago i dont know if this is a problem.

**Comment by kubiiikk** [comment]
@GC-spigot Hi, is there any update for this problem? Seasons are still half functional regardless of version. Whether I have the plugin updated to the latest version or not, it doesn't matter at all, February will pass easily 3 times in a row and immediately after that it will skip straight to winter, after that only manual setting of the month via the command will help. Although the issue is still open as a bug, it has been almost 3 months without any correction of my problems. So will anything happen with it? Thanks.

**Comment by efor89** [comment]
i dont know a lot of time the season not change and i have to do it by my self

**Comment by efor89** [comment]
the season change works now much better
