### ISSUE TITLE
Time doesn't progress in winter

### ISSUE THREAD

**Issue by Pilvinen** [AdvancedPlugins/Seasons#93]
### Describe the bug

Spigot with Minecraft 1.20.6
Latest AdvancedSeasons.
ProtocolLib dev [#689] May 6, 2024, 5:02 PM

Days don't advance in winter. It's always the first day of winter.

No errors on console. Nothing in logs.

### How to reproduce

- Install Spigot 1.20.6 and dev version of protocolLib that runs on 1.20.6
- Install AdvancedSeasons.
- Set season to winter.

**Comment by Pilvinen** [comment]
On closer look it's possible this is caused on my server by setting /gamerule doDaylightCycle false and then progressing the time manually every X tick.

However, on setting /gamerule doDaylightCycle true it seems that calendar.yml settings don't really do anything. The day in the game is vanilla Minecraft length even when I set settings such as:

```
time:
# In Vanilla: entire day in normal minecraft is 20 minutes
spring:
# Length of day time, in real world minutes
dayLength: 40
nightLength: 40
summer:
dayLength: 60
nightLength: 20
fall:
dayLength: 40
nightLength: 40
winter:
dayLength: 28
nightLength: 52

# Seasons Progression
progression:
# Should season progression be paused? Set to true to pause
paused: false

calendar:
# How many days should one season last
seasonDays: 2
# How many days should it take to transition between seasons?
transitionDays: 1
```

Overall I would say that AdvancedSeasons on Minecraft 1.20.6 is pretty much almost entirely broken.

And I would hope that this situation gets some immediate attention.

**Comment by Pilvinen** [comment]
No. I double checked. Apparently I was wrong. During winter the calendar progression completely stops and setting /gamerule doDaylightCycle false doesn't seem to affect that.

So the calendar.yml settings not taking effect seems like a separate issues and I'll open a new ticket on that.

**Comment by Ynverxe** [comment]
https://github.com/AdvancedPlugins/Seasons/issues/95

Your calendar.yml is wrong. You cannot make a MC day during more than 20 minutes. I don't saying that this is the cause of the bug, If it persists, come back here and send all your config files, and your logs/latest.log if it's possible.

**Comment by Pilvinen** [comment]
Setting calendar.yml to default settings did not fix the issue on my main server.
But time progression does seem to work on my test server with only ProtocolLib and AdvancedSeasons with default config.

So, I'm not sure what breaks it at my main server. I guess I will have to start going over all the AdvancedSeasons settings and see if I can get it to break on my test server.

**Comment by Ynverxe** [comment]
This bug doesn't happens on PaperMC. But it was fixed, wait for the next update.

**Comment by Pilvinen** [comment]
Still having this problem in 1.3.0. When it's winter it's always the first day of winter. I haven't been able to figure out which setting might cause this.
